### ISSUE TITLE
add a function tft.pushimage(int32_t tx, int32_t ty, int32_t sx, int32_t sy, int32_t sw, int32_t sh);

### ISSUE THREAD

**Issue by ESPboy-edu** [Bodmer/TFT_eSPI#1098]
Is it possible to add a function:

// Push a windowed area of the image from RAM or PROGMEM to the TFT at tx, ty
tft.pushimage(int32_t tx, int32_t ty, int32_t sx, int32_t sy, int32_t sw, int32_t sh);

which will work like this
// Push a windowed area of the sprite to the TFT at tx, ty
pushSprite(int32_t tx, int32_t ty, int32_t sx, int32_t sy, int32_t sw, int32_t sh);

Thanks.

**Comment by Bodmer** [comment]
This can be achieved by setting up a temporary  viewport area on the screen. See examples.

This avoids the proliferation of function variants. The windowed sprite function was added before the viewport capability was developed. Viewports provide a much more flexible approach since then any graphics can be cropped to a particular screen area.
