### ISSUE TITLE
(question / suggestion) Esp8266 with 8-bit parallel LCD and 74hc595.

### ISSUE THREAD

**Issue by limaomerces** [Bodmer/TFT_eSPI#1134]
I have already read some topics on the subject, but because I already have long dates and have not been conclusive, I would like to know:
Is there already support (or the intention to produce) for parallel communication using shift register (74hc595) ?

**Comment by Bodmer** [comment]
There is no support for a simple shift register circuit that I suspect you are thinking about.
The library does support the 16 bit shift register based Raspberry Pi displays by using the SPI output of the processor, this works because the circuit generates the required write pulse every 16 clocks.
The simplest solution is to buy an SPI based display.
