### ISSUE TITLE
Add pushScaled(); request

### ISSUE THREAD

**Issue by ESPboy-edu** [Bodmer/TFT_eSPI#1239]
Hello
sometimes it's necessary to scale images and sprites

maybe it is possible to add 4/8/16 bit images (RAM/PROGMEM) smooth scaling support for 
pushing to display/sprite someday.

I'll try to code this also

**Comment by Bodmer** [comment]
Scaling would be a nice to have feature even though I do not hve a need for it. This is not a feature I plan to add due to time contraints. You may find suitable 2D transformation code could be used as a basis. It would be nice to write a 2D transformation library but my free time is limited due to other commitments.
