### ISSUE TITLE
readRect and pushRect don't work!

### ISSUE THREAD

**Issue by pbecchi** [Bodmer/TFT_eSPI#134]
I am trying to move a screen 20x20 area to another screen point. All what I get is a black square!
I am using a 3.5 RPi ili9486 SPi Tft.
The code look like this:
`int16_t data[400];  
tft.readRect(100,100,20,20,data);  
tft.pushRect(150,150,20,20,data);`

**Comment by Bodmer** [comment]
The RPi TFT is write only and does not permit reading of the CGRAM. This is a limitation of the RPi screen design.

The readRect() works OK with ILI9341 SPI and UNO style 8 bit parallel displays.

I hope to find time to write a user manual for the library but I am very busy with paid work at the moment!

**Comment by pbecchi** [comment]
Thanks...a manual coul be very usefull....does ili9488 allow reading CGRAM?

**Comment by Bodmer** [comment]
Yes, but the TFT driver can be configured for bidirectional SPI or separate MISO and MOSI signals so it is a bit hit and miss when ordering a display. I have not got it working at all on some displays, possible due to some timing issue or undocumented display configuration made at PCB level.

The only displays I have tested the reading of CGRAM are the ILI9341 SPI and ILI9481 8but parallel displays. Reading the CGRAM on an SPI display is very slow.  I recommend using an UNO style ESP32 and UNO style TFT if reading CGRAM is a must have feature for your sketch.

**Comment by pbecchi** [comment]
Ok thanks again .....I will make some trial and let you know the results.
Where a can find how to configure bidirectional SPI? It should not be by default?
