### ISSUE TITLE
Use GPIO16 for TOUCH_CS

### ISSUE THREAD

**Issue by abdollahpour** [Bodmer/TFT_eSPI#137]
I need to use GPIO4 (which is default pin for TOUCH_CS) for some other things. Is it possible to use GPIO16 too? Since GPIO16 and GPIO4 have some slight differences I'm afraid it cause a problem using the library.

**Comment by Bodmer** [comment]
The library uses the slower digitalWrite(..) function for the touch chip select since performance is dominated by other factors, thus you should be able to use any GPIO pin for that function.

Some pins on the ESP8266 control the boot mode, so make sure these are not pulled low by any connected circuits during the startup of the sketch.

**Comment by abdollahpour** [comment]
Thanks for the details. It was very useful.
