### ISSUE TITLE
Calibration issues with ESP32 and ILI9488 display

### ISSUE THREAD

**Issue by ColinHMurdoch** [Bodmer/TFT_eSPI#1388]
I am building a project using an ESP32 WROOM development board and a 3.5” 480 x 320 SPI display.  According to the supplier this is an ILI9488 display.  
The screen is wired using the normal pin configurations as shown in the User_Setup.h and both the TFT display and the touch screen are working.  However there are issues with the calibration.
When running a test program, touching the screen with a pointer, displays a white dot on a black background.  At the centre left hand side of the screen the white dot appears under the pointer.  As you move to the top of the screen the dot appears a few mm. above the pointer, and as you move down the dot moves a few mm. below the pointer.  As you move to the right the dot moves to the right and as you reach towards the right hand side, the dot moves to about 10mm. away and disappears off the screen.  This effect means that buttons do not work correctly.  For instance the “Keypad_480x320” sketch only works with keys 1,4 & 7 which are on the left hand side.

This is clearly a calibration issue, and I have run the calibration several times to no avail.  I have also captured the calibration numbers and inserted them into the sketch instead of using the SPIFFS file, but this makes no difference.

Is there any way I can adjust the calibration setting to adjust for this?

Any help would be appreciated.

regards,
Colin Murdoch.

**Comment by Bodmer** [comment]
Hi Colin, this is odd as the calibration activity should sort out the calibration factors. The only caveat is that the screen must be calibrated in the rotation that you will use in the final sketch.

Have you tried using the "examples>Generic>Touch_calibrate" sketch?

**Comment by ColinHMurdoch** [comment]
Hi.  Thanks for the feedback.  I'll give that a try and let you know the outcome.

**Comment by ColinHMurdoch** [comment]
Hi Bodmer,
I have repeated this, but still with the result reported earlier.  This is the sketch I modified to play around with the calibration factors.
Firstly I used one of the routines to display the coordinates of each point.  In screen orientation (1) I got the following:
Top left x 3500 y 256 z 1700
Top right x 3500 y 3700 z 890
Bottom left x 490 y 320 z 1500
Bottom right x 490 3600 z 300
I then used the touch_calibrate to catch the calibration figures and got the following in screen orientation (0):
{498, 2852, 256, 3403, 0}.
Using these factors displayed the same result.  I played around and found that
{490, 3200, 320, 3400, 0}
produced near enough the correct result.  It’s not perfect, but as I will be using buttons, as long as the button is large enough this should work OK.
The screen supplier has made available the routines they use to test the screen so I will download those and see if they produce any different result, however I would prefer to co tinge using your library.
Does any of this help?
Regards.

**Comment by Gabryxx** [comment]
I changed the Calibration file, I added a button to reset the calibration, moreover, by pressing with the pen on the display you can see the X and Y coordinates in the center of the screen, and the command line to set the screen is displayed (with the calData coordinates).
I use the screen in mode 3 (landscape), with Esp32 Dev Kit 1 and Ili9488 touchscreen.
Thanks to Bodmer for this library, even if a tutorial on how to connect Esp32 to the screen is missing, I try to attach the file that I used, also I am trying to combine the instructions in a PDF with bookmarks of the various instructions ... coming soon
![Connessione1](https://user-images.githubusercontent.com/36180058/140260415-b09e0fb4-6cab-4f9f-b487-322f8615bbb3.png)

`#include "FS.h"
#include <SPI.h>
#include <TFT_eSPI.h>
TFT_eSPI tft = TFT_eSPI();
// REPEAT CALIBRATION IF YOU CHANGE SCREEN ORIENTATION.
// This is the file name used to store the calibration data
// You can change this to create new calibration files.
// The SPIFFS file name must start with "/".
//#define CALIBRATION_FILE "/TouchCalData2"
// USARE QUESTI COMANDI in setup(): PER SCHERMO 2 VERTICALE (portrait)
// uint16_t calData[5] = { 225, 3527, 272, 3631, 2 };
// tft.setTouch(calData);
#define CALIBRATION_FILE "/TouchCalData3"
// USARE QUESTI COMANDI in setup(): PER SCHERMO 3 ORIZZONTALE (landscape)
// Use this calibration code in setup():
//uint16_t calData[5] = { 224, 3706, 225, 3600, 1 };
//tft.setTouch(calData);

// Keypad start position, key sizes and spacing
#define KEY_X 0 // X Button position it is defined after in drawButtons()
#define KEY_Y 0 // Y Button position it is defined after in drawButtons()
#define KEY_W 0 // Width and height it is defined after in drawButtons()
#define KEY_H 0 /
#define KEY_SPACING_X 0 // X and Y gap
#define KEY_SPACING_Y 0
#define KEY_TEXTSIZE 1   // Font size multiplier
//#define BUTTON_X_DELTA 22
#define NUM_KEYS 1// How many BUTTONS need
TFT_eSPI_Button key[NUM_KEYS];
// Set ripeto to 2 instead of 1 to run calibration
int ripeto = 1 ;
uint16_t calData[5];
void setup() {
  Serial.begin(115200);
  tft.init();
  // Set the rotation before we calibrate
  tft.setRotation(3);
  // Check for backlight pin if not connected to VCC
#ifndef TFT_BL
  Serial.println("No TFT backlight pin defined");
#else
  pinMode(TFT_BL, OUTPUT);
  digitalWrite(TFT_BL, HIGH);
#endif
  // call screen calibration
  touch_calibrate();
  // Clear screen
  tft.fillScreen(TFT_BLACK);
  //tft.setFreeFont(&FreeSerif9pt7b );
  drawButtons();
}

void loop() {
  uint16_t x, y;
  // See if there's any touch data for us
  if (tft.getTouch(&x, &y))  {
    if (key[0].contains(x, y)) {
      ripeto = 2;
      touch_calibrate();
      ripeto = 1;
      tft.fillScreen(TFT_BLACK);
      drawButtons();
    }
    // tft.fillScreen(TFT_BLACK);
    //drawButtons();
    // Draw a block spot to show where touch was calculated to be
    //tft.fillCircle(x, y, 1, TFT_WHITE);
    tft.drawPixel(x, y, TFT_WHITE);
    tft.setTextDatum(4); //4 = centrato
    String stringa = String(x) + "," + String(y);
    tft.setTextColor(TFT_BLACK, TFT_BLACK); tft.drawString("                            ", 230, 160, 1); //cancello vecchia scritta
    tft.setTextColor(TFT_YELLOW, TFT_BLACK); tft.drawString(stringa, 240, 160, 1);   //STRINGA testo,x,y,numero font
    tft.setTextDatum(0); //4 = centrato     DATUM 0 = Top left (default)
    tft.drawString("Use this calibration code in setup():", 10, 290, 1);
    tft.drawString("uint16_t calData[5] = {", 10, 300, 1);
    int aggiungoX = 0;
    for (uint8_t i = 0; i < 5; i++) {
      // tft.drawNumber(calData[i], (150 + aggiungoX), 300, 1);
      String str =  String(calData[i], DEC);
      tft.drawString(str, (150 + aggiungoX), 300, 1);
      aggiungoX +=  (tft.textWidth(str, DEC));
      if (i < 4) tft.drawString(", ", 150 + aggiungoX, 300, 1); aggiungoX += 10;
    }
    tft.drawString("};", 150 + aggiungoX - 10, 300, 1);
    tft.drawString("tft.setTouch(calData);", 10, 310, 1);
  }
}
void drawButtons() {
  tft.setTextFont(4);//0,1,2,4
  // Generate buttons with different size X deltas
  for (int i = 0; i < NUM_KEYS; i++)  {
    String Scritta = "Reset Calibration";
    int Larg_Button = tft.textWidth(Scritta);
    int Alt_Font = tft.fontHeight();
    // void TFT_eSPI_Button::initButton(TFT_eSPI *gfx, int16_t x, int16_t y, uint16_t w, uint16_t h, uint16_t outline, uint16_t fill, uint16_t textcolor, char *label, uint8_t textsize)
    key[i].initButton(&tft,
                      240, //KEY_X + 0 * (KEY_W + KEY_SPACING_X),
                      30,  //KEY_Y + i * (KEY_H + KEY_SPACING_Y), // x, y, w, h, outline, fill, text
                      Larg_Button + 16, //KEY_W,
                      Alt_Font * 1.8, //KEY_H,
                      TFT_WHITE, // Outline
                      TFT_BLACK, // Fill
                      TFT_YELLOW, // Text
                      "", // 10 Byte Label
                      KEY_TEXTSIZE);
    // Adjust button label X delta according to array position
    // setLabelDatum(uint16_t x_delta, uint16_t y_delta, uint8_t datum)
    //MC_DATUM = 4 = Middle centre
    key[i].setLabelDatum(0, ((Alt_Font * 1.8) / 6), 4);
    // Draw button and specify label string
    // Specifying label string here will allow more than the default 10 byte label
    key[i].drawButton(false, Scritta); //:drawButton(bool inverted, String long_name)
  }
}
void touch_calibrate() {
  uint8_t calDataOK = 0;
  // check file system exists
  if (!SPIFFS.begin()) {
    Serial.println("Formating file system");
    SPIFFS.format();
    SPIFFS.begin();
    Serial.println("SPIFF FORMATTATO");
  }
  // check if calibration file exists and size is correct
  if (SPIFFS.exists(CALIBRATION_FILE)) {
    if (ripeto == 2) {
      // Delete if we want to re-calibrate
      SPIFFS.remove(CALIBRATION_FILE);
      Serial.print("File di calibrazione "); Serial.print(CALIBRATION_FILE); Serial.println(" CANCELLATO");
    }
    else
    {
      File f = SPIFFS.open(CALIBRATION_FILE, "r");
      if (f) {
        if (f.readBytes((char *)calData, 14) == 14)
          calDataOK = 1;
        Serial.print("Il file di calibrazione N. "); Serial.print(CALIBRATION_FILE); Serial.println(" Contiene");
        Serial.println("// Use this calibration code in setup():");
        Serial.print("  uint16_t calData[5] = {");
        for (uint8_t i = 0; i < 5; i++)
        {
          Serial.print(calData[i]);
          if (i < 4) Serial.print(", ");
        }
        Serial.println(" };");
        Serial.print("  tft.setTouch(calData);");
        Serial.println(); Serial.println();
        f.close();
      }
    }
  }
  if (calDataOK == 1 && ripeto == 1) {
    // calibration data valid
    tft.setTouch(calData);
  } else {
    // data not valid so recalibrate
    Serial.println(" DATI NON VALIDI DEVO RICALIBRARE");
    Serial.println(ripeto);
    Serial.println(calDataOK);

    tft.fillScreen(TFT_BLACK);
    tft.setCursor(20, 0);
    tft.setTextFont(2);
    tft.setTextSize(1);
    tft.setTextColor(TFT_WHITE, TFT_BLACK);
    tft.println("Touch corners as indicated");
    tft.setTextFont(1);
    tft.println();
    if (ripeto == 2) {
      tft.setTextColor(TFT_RED, TFT_BLACK);
      tft.println("Set ripeto to 1 to stop this running again!");
    }
    tft.calibrateTouch(calData, TFT_MAGENTA, TFT_BLACK, 15);
    tft.setTextColor(TFT_GREEN, TFT_BLACK);
    tft.println("Calibration complete!");
    // store data
    File f = SPIFFS.open(CALIBRATION_FILE, "w");
    if (f) {
      f.write((const unsigned char *)calData, 14);
      Serial.print("Salvo il file di calibrazione N. "); Serial.print(CALIBRATION_FILE);
      Serial.println(); Serial.println();
      Serial.println("// Use this calibration code in setup():");
      Serial.print("  uint16_t calData[5] = ");
      Serial.print("{ ");
      for (uint8_t i = 0; i < 5; i++) {
        Serial.print(calData[i]);
        if (i < 4) Serial.print(", ");
      }
      Serial.println(" };");
      Serial.print("  tft.setTouch(calData);");
      Serial.println(); Serial.println();
      f.close();
    }
  }
}
// Basic colours already defined:
//TFT_BLACK       0x0000
//TFT_NAVY        0x000F
//TFT_DARKGREEN   0x03E0
//TFT_DARKCYAN    0x03EF
//TFT_MAROON      0x7800
//TFT_PURPLE      0x780F
//TFT_OLIVE       0x7BE0
//TFT_LIGHTGREY   0xC618
//TFT_DARKGREY    0x7BEF
//TFT_BLUE        0x001F
//TFT_GREEN       0x07E0
//TFT_CYAN        0x07FF
//TFT_RED         0xF800
//TFT_MAGENTA     0xF81F
//TFT_YELLOW      0xFFE0
//TFT_WHITE       0xFFFF
//TFT_ORANGE      0xFDA0
//TFT_GREENYELLOW 0xB7E0
//TFT_PINK        0xFC9F

// Use the following when calling setFont()
// Reserved for GLCD font  // FF0
// To save a lot of typing long names, each font can easily be referenced in the
// sketch in three ways, either with:
//
//    1. Font file name with the & in front such as &FreeSansBoldOblique24pt7b
//       an example being:
//
//       tft.setFreeFont(&FreeSansBoldOblique24pt7b);
//
//    2. FF# where # is a number determined by looking at the list below
//       an example being:
//
//       tft.setFreeFont(FF32);
//
//    3. An abbreviation of the file name. Look at the list below to see
//       the abbreviations used, for example:
//
//       tft.setFreeFont(FSSBO24)
//
//       Where the letters mean:
//       F = Free font
//       M = Mono
//      SS = Sans Serif (double S to distinguish is form serif fonts)
//       S = Serif
//       B = Bold
//       O = Oblique (letter O not zero)
//       I = Italic
//       # =  point size, either 9, 12, 18 or 24
//
//  Setting the font to NULL will select the GLCD font:
//
//      tft.setFreeFont(NULL); // Set font to GLCD
//
//#define LOAD_GFXFF
//
//#ifdef LOAD_GFXFF // Only include the fonts if LOAD_GFXFF is defined in User_Setup.h
//
//// Use these when printing or drawing text in GLCD and high rendering speed fonts
//#define GFXFF 1
//#define GLCD  0
//#define FONT2 2
//#define FONT4 4
//#define FONT6 6
//#define FONT7 7
//#define FONT8 8

// Use the following when calling setFont()
//
// Reserved for GLCD font  // FF0
//
//#define TT1 &TomThumb
//
//#define FM9 &FreeMono9pt7b
//#define FM12 &FreeMono12pt7b
//#define FM18 &FreeMono18pt7b
//#define FM24 &FreeMono24pt7b
//
//#define FMB9 &FreeMonoBold9pt7b
//#define FMB12 &FreeMonoBold12pt7b
//#define FMB18 &FreeMonoBold18pt7b
//#define FMB24 &FreeMonoBold24pt7b
//
//#define FMO9 &FreeMonoOblique9pt7b
//#define FMO12 &FreeMonoOblique12pt7b
//#define FMO18 &FreeMonoOblique18pt7b
//#define FMO24 &FreeMonoOblique24pt7b
//
//#define FMBO9 &FreeMonoBoldOblique9pt7b
//#define FMBO12 &FreeMonoBoldOblique12pt7b
//#define FMBO18 &FreeMonoBoldOblique18pt7b
//#define FMBO24 &FreeMonoBoldOblique24pt7b
//
//#define FSS9 &FreeSans9pt7b
//#define FSS12 &FreeSans12pt7b
//#define FSS18 &FreeSans18pt7b
//#define FSS24 &FreeSans24pt7b
//
//#define FSSB9 &FreeSansBold9pt7b
//#define FSSB12 &FreeSansBold12pt7b
//#define FSSB18 &FreeSansBold18pt7b
//#define FSSB24 &FreeSansBold24pt7b
//
//#define FSSO9 &FreeSansOblique9pt7b
//#define FSSO12 &FreeSansOblique12pt7b
//#define FSSO18 &FreeSansOblique18pt7b
//#define FSSO24 &FreeSansOblique24pt7b
//
//#define FSSBO9 &FreeSansBoldOblique9pt7b
//#define FSSBO12 &FreeSansBoldOblique12pt7b
//#define FSSBO18 &FreeSansBoldOblique18pt7b
//#define FSSBO24 &FreeSansBoldOblique24pt7b
//
//#define FS9 &FreeSerif9pt7b
//#define FS12 &FreeSerif12pt7b
//#define FS18 &FreeSerif18pt7b
//#define FS24 &FreeSerif24pt7b
//
//#define FSI9 &FreeSerifItalic9pt7b
//#define FSI12 &FreeSerifItalic12pt7b
//#define FSI19 &FreeSerifItalic18pt7b
//#define FSI24 &FreeSerifItalic24pt7b
//
//#define FSB9 &FreeSerifBold9pt7b
//#define FSB12 &FreeSerifBold12pt7b
//#define FSB18 &FreeSerifBold18pt7b
//#define FSB24 &FreeSerifBold24pt7b
//
//#define FSBI9 &FreeSerifBoldItalic9pt7b
//#define FSBI12 &FreeSerifBoldItalic12pt7b
//#define FSBI18 &FreeSerifBoldItalic18pt7b
//#define FSBI24 &FreeSerifBoldItalic24pt7b
//
//#define FF0 NULL //ff0 reserved for GLCD
//#define FF1 &FreeMono9pt7b
//#define FF2 &FreeMono12pt7b
//#define FF3 &FreeMono18pt7b
//#define FF4 &FreeMono24pt7b
//
//#define FF5 &FreeMonoBold9pt7b
//#define FF6 &FreeMonoBold12pt7b
//#define FF7 &FreeMonoBold18pt7b
//#define FF8 &FreeMonoBold24pt7b
//
//#define FF9 &FreeMonoOblique9pt7b
//#define FF10 &FreeMonoOblique12pt7b
//#define FF11 &FreeMonoOblique18pt7b
//#define FF12 &FreeMonoOblique24pt7b
//
//#define FF13 &FreeMonoBoldOblique9pt7b
//#define FF14 &FreeMonoBoldOblique12pt7b
//#define FF15 &FreeMonoBoldOblique18pt7b
//#define FF16 &FreeMonoBoldOblique24pt7b
//
//#define FF17 &FreeSans9pt7b
//#define FF18 &FreeSans12pt7b
//#define FF19 &FreeSans18pt7b
//#define FF20 &FreeSans24pt7b
//
//#define FF21 &FreeSansBold9pt7b
//#define FF22 &FreeSansBold12pt7b
//#define FF23 &FreeSansBold18pt7b
//#define FF24 &FreeSansBold24pt7b
//
//#define FF25 &FreeSansOblique9pt7b
//#define FF26 &FreeSansOblique12pt7b
//#define FF27 &FreeSansOblique18pt7b
//#define FF28 &FreeSansOblique24pt7b
//
//#define FF29 &FreeSansBoldOblique9pt7b
//#define FF30 &FreeSansBoldOblique12pt7b
//#define FF31 &FreeSansBoldOblique18pt7b
//#define FF32 &FreeSansBoldOblique24pt7b
//
//#define FF33 &FreeSerif9pt7b
//#define FF34 &FreeSerif12pt7b
//#define FF35 &FreeSerif18pt7b
//#define FF36 &FreeSerif24pt7b
//
//#define FF37 &FreeSerifItalic9pt7b
//#define FF38 &FreeSerifItalic12pt7b
//#define FF39 &FreeSerifItalic18pt7b
//#define FF40 &FreeSerifItalic24pt7b
//
//#define FF41 &FreeSerifBold9pt7b
//#define FF42 &FreeSerifBold12pt7b
//#define FF43 &FreeSerifBold18pt7b
//#define FF44 &FreeSerifBold24pt7b
//
//#define FF45 &FreeSerifBoldItalic9pt7b
//#define FF46 &FreeSerifBoldItalic12pt7b
//#define FF47 &FreeSerifBoldItalic18pt7b
//#define FF48 &FreeSerifBoldItalic24pt7b`

**Comment by ColinHMurdoch** [comment]
Hi Bodmer,  sorry for the slow reply.
I downloaded the test files supplied by the screen retailer, but they were sketches for running on Uno or Mega.  I had my ESP32/screen setup working OK by then so did not wish to break it down to test on the Uno.
I have now written some code for the project I am working on (a battery powered WiFi throttle for DCC model railway operation) and this shows that my fudge on the calibration works OK.  With 12 buttons in the lower 2/3 of the screen the buttons respond correctly.  Still more code to write as I have multiple screens to deal with but it suggests that all works satisfactorily for my project.  When this project is complete I will probably build a duplicate, so it will be interesting to see if an identical screen behaves in the same way.  It is possible that the one I have at present has some slight fault.
Not a very conclusive result from the original fault but I am happy with the project as it is now.  I suggest that you close this call off.
Many thanks for the library, and for all the assistance you give to everyone.
Regards,
Colin Murdoch.

**Comment by Bodmer** [comment]
Glad you resolved this.
