### ISSUE TITLE
Framebuffer for 320x480 px display

### ISSUE THREAD

**Issue by DIYLAB-DE** [Bodmer/TFT_eSPI#1407]
For my project, I want to use a third-party GFX library.
The reason for this is that I could then port already existing code to TFT_eSPI very easily.
This GFX library requires that it can write to a framebuffer - so far no problem!
Now I am faced with the challenge of setting up a framebuffer of size 320x480*2 on the ESP32.
This works very well on the Teensy 4.x, of course not on the ESP32 :/

**_How could I solve this with TFT_eSPI?_**

First of all, I don't know how to realize a framebuffer of smaller size, which switches the areas to be drawn by itself.

Best
Bruno

*Additional info: I am using an ILI9486 display in 8-bit parallel mode and an ESP32-WROOM-32. An ESP32-WROVER with PSRAM would also be available.

**Comment by Bodmer** [comment]
TFT_eSPI provides Sprites that can be used as frame buffers. The DMA Bouncy_Circles sketch should run on an 240x320 display. As you have a 480x320 display you will need to modify the sketch so that it does not use tft.width() or tft.height(), but 240 and 320 instead.

Sprites can also use 8 bit colour depth of 4 bit (with a colour palette) see examples.
