### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by JakubRybakowski** [Bodmer/TFT_eSPI#1456]
Hello, we want to support different languages ​​in our device. Therefore, we need fonts that contain different characters. I prepared vlw fonts in various sizes. Together, however, their size is significantly too large. It won't fit in our flash drive.

I would not like to prepare separate software for each language containing a given font.

What's the best approach to this topic?

Is it possible to use ttf or any other format that allows to scale fonts??

**Comment by Bodmer** [comment]
The vlw font format does use a lot of space for large font sets that contain a high glyph count.

Some users put fonts on SD cards instead of FLASH but this is typically less convenient.

Ways to reduce memory are:
1. Reduce the point size of the font (halving the pint size reduces memory demands by 4 times due to area.
2. Reduce the glyph count to those needed. Fonts often contain caharacters that are rarely or never used.
3. If halving the font size would help then you could try the 4 bit font method proposed in #1345 
4. Use a pitmap (not anti-aliased) font,[ see here](https://github.com/Bodmer/U8g2_for_TFT_eSPI) for an option.
