### ISSUE TITLE
Trouble with Sprite in large program

### ISSUE THREAD

**Issue by MikeyMoMo** [Bodmer/TFT_eSPI#1487]
I am using a Sprite like a Canvas for text.  I was using Canvas but it uses the Adafruit (*.7b) fonts, is slower than Sprite and I have to duplicate the fonts for TFT (.vlw) and Canvas (.7b).  So I switched to Sprite.  I have one that is currently 480 x 57 that I put text in.  It was default but I now set it to 8 bit.  Just 2 color text.  When I use it at that size, all is well.  I can push it onto the screen and it looks right.  No flicker and fast updating.  But I wanted to go ahead and make it full screen, 320x480, and put all of the text on that one Sprite.  When I do this, it devolves into a single rectangle at 0,0 (upper left corner) and the width and height of one character of the font.  I can see all of the characters run, in order, through that rectangle, rapidly, ending on the last character that remains showing.

This happened previously when I was running SerialBT.  I read somewhere that it might be a stack problem so I took that part totally out of the program and the Sprite started working properly again.  Then this second occurrence of the same situation.

The program uses about 62% of 3 Meg and 12% of variable storage.  I think there was 6.5K in the stack last I checked.  I am using the Arduino IDE for this project.  I don't know where the work space is allocated.  Will look, later.

What can I check for and change to make the Sprite work properly?  All of the other stuff works just fine, like touch and the clicking and swiping code I wrote.  It is just Sprite that is being odd.  I can post pictures of this on FB in the ESP32 group if you would like to see how it looks.

After adding a little code, it seems that the calloc is failing.  When I allocate 320x57, createSprite returns a pointer to 0x3ffc828c.  When I allocate the fill 320x480, createSprite returns a pointer to 0x0.

Sketch uses 1919350 bytes (61%) of program storage space. Maximum is 3145728 bytes.
Global variables use 42180 bytes (12%) of dynamic memory, leaving 285500 bytes for local variables. Maximum is 327680 bytes.

Thanks for an otherwise most excellent library!

Mike Morrow

**Comment by Bodmer** [comment]
Unfortunately the ESP32 reserves a lot less memory than expected for Arduino sketches, I suspect this is due to the underlying RTOS and the reservation of RAM for the second processor. My experiments indicate a 200x200 16 bit Sprite (80kbytes) is about the biggest I could use before problems with RAM show up. The null pointer 0x0 indicates the RAM could not be reserved.

At compile time only the variable storage figure is given, not what could be dynamically allocated during run time.

One option is to use an ESP32 with PSRAM as then larger sprites can be used. However due to caching from the serial PSRAM to local memory the performance will reduces once the sprite size is more than about 32kbytes.
