### ISSUE TITLE
Installed 2.4.2, getting odd message

### ISSUE THREAD

**Issue by MikeyMoMo** [Bodmer/TFT_eSPI#1524]
TFT_eSPI tft = TFT_eSPI(); // Invoke custom library

call to 'TFT_eSPI::TFT_eSPI(int16_t, int16_t)' uses the default argument for parameter 1, which is not yet defined 

No change in the code.  Went back to 3.70 and working just fine again.

**Comment by Bodmer** [comment]
It looks like TFT_WIDTH and TFT_HEIGHT are not defined for some reason.

This may be processor or display driver specific as I am not seeing that message.

Can you tell me which processor you are using and which display driver.

**Comment by mrjgreg** [comment]
Similar here:
Example.....
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
In file included from /home/pi/Arduino/libraries/TFT_eSPI/examples/320 x 240/TFT_graphicstest_one_lib/TFT_graphicstest_one_lib.ino:17:
/home/pi/Arduino/libraries/TFT_eSPI/TFT_eSPI.h:391:25: error: 'TFT_WIDTH' was not declared in this scope; did you mean 'TFT_WHITE'?
  391 |   TFT_eSPI(int16_t _W = TFT_WIDTH, int16_t _H = TFT_HEIGHT);
      |                         ^~~~~~~~~
      |                         TFT_WHITE
/home/pi/Arduino/libraries/TFT_eSPI/TFT_eSPI.h:391:49: error: 'TFT_HEIGHT' was not declared in this scope
  391 |   TFT_eSPI(int16_t _W = TFT_WIDTH, int16_t _H = TFT_HEIGHT);
      |                                                 ^~~~~~~~~~
exit status 1
Error compiling for board Raspberry Pi Pico.
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Board RPI Pico2040
ILI9341 display

Setup 60  <now 61> modified for user specific GPIO

All worked OK before update ?

Cheers
MrGreg

**Comment by Bodmer** [comment]
Which version of the library are you using?

**Comment by mrjgreg** [comment]
Hello
It was the latest update installed on 5 Jan 22
ver 2.4.2
On arduino ver 1.8.13 ( debian repo version )
Cheers
MrGreg

**Comment by Bodmer** [comment]
Which board package are you using (Earle Philhower's or the Arduino Mbed one)?

**Comment by mrjgreg** [comment]
The Earle Philhower's one

**Comment by Bodmer** [comment]
Post your complete setup file.

**Comment by mrjgreg** [comment]
Just noticed there is an another update to Earle Philhower board. Will try that first and report back...

Cheers
MrGreg

**Comment by mrjgreg** [comment]
Same result again with updated board;

Here is the setup:
xxxxxxxxxxxxxxxxxxxxxxxxxxx

//                            USER DEFINED SETTINGS
//   Set driver type, fonts to be loaded, pins used and SPI control method etc
//
//   See the User_Setup_Select.h file if you wish to be able to define multiple
//   setups and then easily select which setup file is used by the compiler.
//
//   If this file is edited correctly then all the library example sketches should
//   run without the need to make any more changes for a particular hardware setup!
//   Note that some sketches are designed for a particular TFT pixel width/height


// ##################################################################################
//
// Section 1. Call up the right driver file and any options for it
//
// ##################################################################################

// Tell the library to use 8 bit parallel mode (otherwise SPI is assumed)
//#define TFT_PARALLEL_8_BIT

// Display type -  only define if RPi display
//#define RPI_DISPLAY_TYPE // 20MHz maximum SPI

// Only define one driver, the other ones must be commented out
#define ILI9341_DRIVER
//#define ST7735_DRIVER      // Define additional parameters below for this display
//#define ILI9163_DRIVER     // Define additional parameters below for this display
//#define S6D02A1_DRIVER
//#define RPI_ILI9486_DRIVER // 20MHz maximum SPI
//#define HX8357D_DRIVER
//#define ILI9481_DRIVER
//#define ILI9486_DRIVER
//#define ILI9488_DRIVER     // WARNING: Do not connect ILI9488 display SDO to MISO if other devices share the SPI bus (TFT SDO does NOT tristate when CS is high)
//#define ST7789_DRIVER      // Full configuration option, define additional parameters below for this display
//#define ST7789_2_DRIVER    // Minimal configuration option, define additional parameters below for this display
//#define R61581_DRIVER
//#define RM68140_DRIVER
//#define ST7796_DRIVER
//#define SSD1963_480_DRIVER
//#define SSD1963_800_DRIVER
//#define SSD1963_800ALT_DRIVER
//#define ILI9225_DRIVER

// Some displays support SPI reads via the MISO pin, other displays have a single
// bi-directional SDA pin and the library will try to read this via the MOSI line.
// To use the SDA line for reading data from the TFT uncomment the following line:

// #define TFT_SDA_READ      // This option is for ESP32 ONLY, tested with ST7789 display only

// For ST7735, ST7789 and ILI9341 ONLY, define the colour order IF the blue and red are swapped on your display
// Try ONE option at a time to find the correct colour order for your display

//  #define TFT_RGB_ORDER TFT_RGB  // Colour order Red-Green-Blue
//  #define TFT_RGB_ORDER TFT_BGR  // Colour order Blue-Green-Red

// For ST7789, ST7735 and ILI9163 ONLY, define the pixel width and height in portrait orientation
// #define TFT_WIDTH  80
// #define TFT_WIDTH  128
// #define TFT_WIDTH  240 // ST7789 240 x 240 and 240 x 320
// #define TFT_HEIGHT 160
// #define TFT_HEIGHT 128
// #define TFT_HEIGHT 240 // ST7789 240 x 240
// #define TFT_HEIGHT 320 // ST7789 240 x 320

// For ST7735 ONLY, define the type of display, originally this was based on the
// colour of the tab on the screen protector film but this is not always true, so try
// out the different options below if the screen does not display graphics correctly,
// e.g. colours wrong, mirror images, or tray pixels at the edges.
// Comment out ALL BUT ONE of these options for a ST7735 display driver, save this
// this User_Setup file, then rebuild and upload the sketch to the board again:

// #define ST7735_INITB
// #define ST7735_GREENTAB
// #define ST7735_GREENTAB2
// #define ST7735_GREENTAB3
// #define ST7735_GREENTAB128    // For 128 x 128 display
// #define ST7735_GREENTAB160x80 // For 160 x 80 display (BGR, inverted, 26 offset)
// #define ST7735_REDTAB
// #define ST7735_BLACKTAB
// #define ST7735_REDTAB160x80   // For 160 x 80 display with 24 pixel offset

// If colours are inverted (white shows as black) then uncomment one of the next
// 2 lines try both options, one of the options should correct the inversion.

// #define TFT_INVERSION_ON
// #define TFT_INVERSION_OFF


// ##################################################################################
//
// Section 2. Define the pins that are used to interface with the display here
//
// ##################################################################################

// If a backlight control signal is available then define the TFT_BL pin in Section 2
// below. The backlight will be turned ON when tft.begin() is called, but the library
// needs to know if the LEDs are ON with the pin HIGH or LOW. If the LEDs are to be
// driven with a PWM signal or turned OFF/ON then this must be handled by the user
// sketch. e.g. with digitalWrite(TFT_BL, LOW);

// #define TFT_BL   32            // LED back-light control pin
// #define TFT_BACKLIGHT_ON HIGH  // Level to turn ON back-light (HIGH or LOW)

// We must use hardware SPI, a minimum of 3 GPIO pins is needed.
// Typical setup for the RP2040 is :
//
// Display SDO/MISO  to RP2040 pin D0 (or leave disconnected if not reading TFT)
// Display LED       to RP2040 pin 3V3 or 5V
// Display SCK       to RP2040 pin D2
// Display SDI/MOSI  to RP2040 pin D3
// Display DC (RS/AO)to RP2040 pin D18 (can use another pin if desired)
// Display RESET     to RP2040 pin D19 (can use another pin if desired)
// Display CS        to RP2040 pin D20 (can use another pin if desired, or GND, see below)
// Display GND       to RP2040 pin GND (0V)
// Display VCC       to RP2040 5V or 3.3V (5v if display has a 5V to 3.3V regulator fitted)
//
// The DC (Data Command) pin may be labelled AO or RS (Register Select)
//
// With some displays such as the ILI9341 the TFT CS pin can be connected to GND if no more
// SPI devices (e.g. an SD Card) are connected, in this case comment out the #define TFT_CS
// line below so it is NOT defined. Other displays such at the ST7735 require the TFT CS pin
// to be toggled during setup, so in these cases the TFT_CS line must be defined and connected.

// For the Pico use these #define lines
//#define TFT_MISO  16
//#define TFT_MOSI  19
//#define TFT_SCLK  18
#define TFT_CS   17  // Chip select control pin
#define TFT_DC   21  // Data Command control pin
#define TFT_RST  20  // Reset pin (could connect to Arduino RESET pin)
//#define TFT_BL     // LED back-light

//#define TOUCH_CS 21     // Chip select pin (T_CS) of touch screen

// ##################################################################################
//
// Section 3. Define the fonts that are to be used here
//
// ##################################################################################

// Comment out the #defines below with // to stop that font being loaded
// The ESP8366 and ESP32 have plenty of memory so commenting out fonts is not
// normally necessary. If all fonts are loaded the extra FLASH space required is
// about 17Kbytes. To save FLASH space only enable the fonts you need!

#define LOAD_GLCD   // Font 1. Original Adafruit 8 pixel font needs ~1820 bytes in FLASH
#define LOAD_FONT2  // Font 2. Small 16 pixel high font, needs ~3534 bytes in FLASH, 96 characters
#define LOAD_FONT4  // Font 4. Medium 26 pixel high font, needs ~5848 bytes in FLASH, 96 characters
#define LOAD_FONT6  // Font 6. Large 48 pixel font, needs ~2666 bytes in FLASH, only characters 1234567890:-.apm
#define LOAD_FONT7  // Font 7. 7 segment 48 pixel font, needs ~2438 bytes in FLASH, only characters 1234567890:-.
#define LOAD_FONT8  // Font 8. Large 75 pixel font needs ~3256 bytes in FLASH, only characters 1234567890:-.
//#define LOAD_FONT8N // Font 8. Alternative to Font 8 above, slightly narrower, so 3 digits fit a 160 pixel TFT
#define LOAD_GFXFF  // FreeFonts. Include access to the 48 Adafruit_GFX free fonts FF1 to FF48 and custom fonts

// Comment out the #define below to stop the SPIFFS filing system and smooth font code being loaded
// this will save ~20kbytes of FLASH
#define SMOOTH_FONT


// ##################################################################################
//
// Section 4. Other options
//
// ##################################################################################

// For the RP2040 processor define the SPI port channel used, default is 0
// #define TFT_SPI_PORT 1 // Set to 0 if SPI0 pins are used, or 1 if spi1 pins used

// Define the SPI clock frequency, this affects the graphics rendering speed. Too
// fast and the TFT driver will not keep up and display corruption appears.
// With an ILI9341 display 40MHz works OK, 80MHz sometimes fails
// With a ST7735 display more than 27MHz may not work (spurious pixels and lines)
// With an ILI9163 display 27 MHz works OK.

// #define SPI_FREQUENCY   1000000
// #define SPI_FREQUENCY   5000000
// #define SPI_FREQUENCY  10000000
// #define SPI_FREQUENCY  20000000
// #define SPI_FREQUENCY  32000000
 #define SPI_FREQUENCY  70000000

// Optional reduced SPI frequency for reading TFT
#define SPI_READ_FREQUENCY  20000000

// The XPT2046 requires a lower SPI clock rate of 2.5MHz so we define that here:
#define SPI_TOUCH_FREQUENCY  2500000



xxxxxxxxxxxxxxxxxxxxxxxxxxxx
Cheers
MrGreg

**Comment by Bodmer** [comment]
You will need to define TFT_MISO, TFT_MOSI and TFT_SCLK for the Pico, but that is not the problem.

Have you changed anything in the User_Setup_Select.h file? For some reason [this line is not being executed ](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setup_Select.h#L152)even though you have defined the display type.

It may be best to load a clean copy of the library.

**Comment by mrjgreg** [comment]
OK.....
FYI Re:" You will need to define TFT_MISO, TFT_MOSI and TFT_SCLK for the Pico, but that is not the problem."
Yes, I was aware. I  was trying them <experimenting> commented out as I have had some previous problems with #defining SPI pins being ignored and reverting to hw defaults of 16,17,18,19.
I'll wipe the Lib and start afresh & report back.

Cheers
MrGreg

**Comment by Bodmer** [comment]
OK. In a clean copy [comment out this line](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setup_Select.h#L22) with //

Then remove // at [start of this line](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setup_Select.h#L82).

Make no other changes.

Save the file and run Read_User_Setup example, the output should be like this:
```
[code]
TFT_eSPI ver = 2.4.2
Processor    = RP2040
Transactions = Yes
Interface    = SPI
Display driver = 9341
Display width  = 240
Display height = 320

MOSI    = GPIO 3
MISO    = GPIO 0
SCK     = GPIO 2
TFT_CS   = GPIO 20
TFT_DC   = GPIO 18
TFT_RST  = GPIO 19

Font GLCD   loaded
Font 2      loaded
Font 4      loaded
Font 6      loaded
Font 7      loaded
Font 8      loaded
Smooth font enabled

Display SPI frequency = 70.00
[/code]

```
Then edit the pins in Setup60_RP2040_ILI9341.h to suit your setup. Run Read_User_Setup again to check the compiler has picked up the new changes correctly.

**Comment by mrjgreg** [comment]
Hmmmmmmmmmm!!

Not done the above yet, But...

"Ghost in the machine"....?
Wiped the lib and reinstalled as suggested, ran my original setup 61 but with SPI defined on 16,17,18,19 as per previous setup.
Now works fine !!! 
This , rather my setup is as it was before the update.
V. curious? as the OP who started the issue had the same symptom?
Can only wild guess that it may have been a corrupt update for what ever reason and is now OK?

Do you still want me to run the above amended  diagnostic?

Cheers
MrGreg

**Comment by Bodmer** [comment]
If it is working then that is great. Typically this error only happens if the display type is not correctly defined or something got deleted by accident.

Glad it is working.

**Comment by Bodmer** [comment]
@MikeyMoMo Can you also follow the advice above and reload TFT_eSPI.

Open a new issue if the problem persists.

**Comment by mrjgreg** [comment]
Hello I would just like to confirm I had not done anything with user_setup_select other than pointing at my setup.
Lastly, perhaps most importantly:
V BIG Thank you for both the most excellent Lib and the support. Much appreciated !

Cheers
MrGreg
