### ISSUE TITLE
Display Stops Working when T_CLK is connected in Overlap Mode

### ISSUE THREAD

**Issue by generalannoyance** [Bodmer/TFT_eSPI#159]
Hey -- basically title. Screen works fine in non-overlap, but in overlap as soon as I connect the T_CLK it stops working. I can leave everything else connected and it'll draw fine. I've double checked  wiring and connectivity. 
Here's my config: 
![image](https://user-images.githubusercontent.com/40320703/41499852-c4839896-7155-11e8-838e-689426664a1e.png)

Thanks in advance for looking at it.

**Comment by Bodmer** [comment]
A restriction of overlap mode is that only one SPI device can be connected, so a touch screen controller cannot also be connected.  This restriction is because in overlap mode the FLASH memory SPI bus is being used so the processor must have hardware control is all SPI devices via the chip select, and there is only one available hardware chip select.

**Comment by generalannoyance** [comment]
Ahh okay, fair enough. Is this mentioned in the documentation anywhere or did I just miss it? Thanks for the response though.
