### ISSUE TITLE
Touch Screen in parallel Mode

### ISSUE THREAD

**Issue by moreauftheobald** [Bodmer/TFT_eSPI#1597]
Hello,

I got a SSD1963 screen whith SPI touch Screen. I've made a few modifications on the library in order to let the library device the spi port in order to be abble to use the touch screen functions of the library.

I'm not sure that my code is great so i will not put it here (in fact i have just removed some line with "#if !defined(TFT_PARALLEL_8_BIT)" in the TFT_eSPI.cpp and in the TFT_eSPI_ESP32.h and TFT_eSPI_ESP32.c.

my setup file has all the parallel pin defined and the spi classic pin (SCK, MISO and MOSI) and off course the TOUCH_CS pin
It works great. and like this i can use your library to manage the touch screen.

Is it possible to implement this into your library ?

**Comment by Bodmer** [comment]
So remove 1 line and it works? If not then can you list the changes.

I do not have a parallel screen with SPI touch but I could patch one together using a parallel sceen and diferent a SPI screen.

**Comment by copyCATandpasteDOG** [comment]
Hi, moreauftheobald ,

I would like to use it too,but playing  removing lines with "#if !defined(TFT_PARALLEL_8_BIT)"
makes a lot of errors in arduino like : error: #endif without #if

Could you please show us or allow us download the specified files you modified,with the ssd1963setup file too.
You can make a zip file with all of them.
Thanks in advance :)

**Comment by moreauftheobald** [comment]
Here's my version of the library witch working .... i think it will only work with ESP32, and it could not work with only 8 Bit parallel and no spi touch screen, but i think that someone with better knowledge in programming could arrange this.

my setup is in user setup <Setup00_SSD1963_Parallel.h>

[TFT_eSPI.zip](https://github.com/Bodmer/TFT_eSPI/files/7981567/TFT_eSPI.zip)
.
hope it could help

**Comment by copyCATandpasteDOG** [comment]
Hi  moreauftheobald ,
Made a lot of tests and tryings,but i have the same issues,even if by now, there is no error from arduino
if i select "#define TOUCH_CS 5" in the setup.
It's impossible for me to have twice the touch working with the video picture,and the weird thing is that
my touch pin is not connected,but react when i set it to 5 in the setup,it must be interally connected
in the TFT! 
Maybe bodmer can explain that strange thing.
To resume,touch works alone,and the  picture works alone too ,but never the twice together like in the
"keypad" sketch.
Why don't you make a little video with your success and post it here :)

**Comment by Bodmer** [comment]
You should be able to use other SPI touch libraries with an 8 bit parallel screen driven by TFT_eSPI.

**Comment by copyCATandpasteDOG** [comment]
Hi Bodmer,
i'm glad i succeeded using TFT TOUCH and TFT_eSPI together,but it needs a lot of pins!!
I had to wait until i get a esp32 wroover dev kit 1.
I had to pass over the warnings telling it's maybe not for esp32 architecture,and the sketch says
the pins number are for mega and dedicated for ILI9341,that's why i didn't try it before. 
Now that it's done i encounter another problem:
the calibration of the library does not satisfy me at all and the result with the draw sketch is very bad.
In the calibration sketch,in the void setup all rotations are (1) but in the monitor the result shows:


First point : Raw x,y = 860,1396 (up left)
Second point : Raw x,y = 1896,2019 (center)
Third point : Raw x,y = 3687,3519 (down right) but very hard to press to get a value,why? 
Fourth point : Raw x,y = 1919,1991 (center)
Fifth point : Raw x,y = 440,3099 (down left) but very hard to press to get a value,why?

 --------------then final result : ---------------

touch.setCal(860, 3687, 1396, 3519, 800, 480, 0);
wich indicate a rotation of (0)???
This result looks like (x(up left),x(down right),y(up right),y(down right));

Then in the draw sketch i tried with (0) then (1) for the rotations but it was bad.
There is a distorsion distance maybe because the rotation difference but i can't face it

Do you have a good valuable result i can try with the draw sketch?
I think all SSD1963 7INCH resistive have all the  same results

**Comment by copyCATandpasteDOG** [comment]
Later...
Made some experimentations:
the calibration line : touch.setCal(516, 3565, 1118, 3320, 800, 480, 0);
doesn't do anything in the draw sketch,so i erased it.
The y coarse was inverted and i corrected it :   Y_Coord = 170 - touch.Y();
The x coarse has been a little corrected :   X_Coord = touch.X()- 50;

My goal is to make a button sensitive commands and i succeeded with,don't need drawing stuff :)
here is the sketch with 4 buttons:

//------------------------------------------------------------------


 //Button test with SSD1963 & ESP32 Wroover Dev Kit 1

#include <SPI.h>
#include <TFT_eSPI.h>
TFT_eSPI tft = TFT_eSPI();


// Call up touch screen library
#include <TFT_Touch.h>


// These are the pins used to interface between the 2046 touch controller and Arduino Pro
#define DOUT 19  /* Data out pin (T_DO) of touch screen */
#define DIN  23  /* Data in pin (T_DIN) of touch screen */
#define DCS  20  /* Chip select pin (T_CS) of touch screen */
#define DCLK 18  /* Clock pin (T_CLK) of touch screen */

/* Create an instance of the touch screen library */
TFT_Touch touch = TFT_Touch(DCS, DCLK, DIN, DOUT);


void setup()
{
  Serial.begin(115200);

  tft.init(); 

  
  // Set the TFT and touch screen to landscape orientation
  tft.setRotation(1);
  touch.setRotation(1);

  tft.fillScreen(TFT_BLACK);

 tft.fillRect(50, 100, 100, 150, TFT_WHITE);
 tft.fillRect(150, 100, 100, 150, TFT_BLUE);
 tft.fillRect(250, 100, 100, 150, TFT_GREEN);
 tft.fillRect(350, 100, 100, 150, TFT_YELLOW);

      
}


void loop()
{
  int X_RawData;
  int Y_RawData;
  int X_Coord;
  int Y_Coord;

  // Check if the touch screen is currently pressed
  // Raw and coordinate values are stored within library at this instant
  // for later retrieval by GetRaw and GetCoord functions.

  if (touch.Pressed()) // Note this function updates coordinates stored within library variables
  {
    // Read the current X and Y axis as co-ordinates at the last touch time
    // The values were captured when Pressed() was called!
    X_Coord = touch.X()- 50;
    Y_Coord = 170 - touch.Y();

    Serial.print(X_Coord); Serial.print(","); Serial.println(Y_Coord);
    
    //Button test verification on the monitor
    if(X_Coord>30 && X_Coord<50 && Y_Coord>50 && Y_Coord<70)
    Serial.println("WHITE PRESSED!");
    if(X_Coord>50 && X_Coord<70 && Y_Coord>50 && Y_Coord<70)
    Serial.println("BLUE PRESSED!");
    if(X_Coord>70 && X_Coord<90 && Y_Coord>50 && Y_Coord<70)
    Serial.println("GREEN PRESSED!");
    if(X_Coord>90 && X_Coord<110 && Y_Coord>50 && Y_Coord<70)
    Serial.println("YELLOW PRESSED!");
  }
}

//------------------------------------------------------------------

**Comment by copyCATandpasteDOG** [comment]
Finally...

I set up a sketch that fit the TFT 7inch resistive with resolution 800x480
the X coarse in rotation(0) is  inverted and i said the Y coarse in rotation(1) was inverted,
because i always use rotation(1) in the sketch,but it's the same problem.
I change the resolution in the TFT_Touch.cpp :
_hres = 800;
_vres = 480;

hey Bodmer,is it possible to declare the resolution only in the sketch and let the TFT_Touch.cpp blank?
I will post my final sketch in the  TFT_Touch forum.

---------------------------------------------------------------------------------------------------------------


                      //Button test with SSD1963 - 7INCH Resistive & ESP32 Wroover Dev Kit 1
                                     //800x480 in TFT_Touch.cpp  :  _hres = 800  &  _vres = 480                                             
                                           

#include <SPI.h>
#include <TFT_eSPI.h>
TFT_eSPI tft = TFT_eSPI();


// Call up touch screen library
#include <TFT_Touch.h>


// These are the pins used to interface between the 2046 touch controller and Arduino Pro
#define DOUT 19  /* Data out pin (T_DO) of touch screen */
#define DIN  23  /* Data in pin (T_DIN) of touch screen */
#define DCS  20  /* Chip select pin (T_CS) of touch screen */
#define DCLK 18  /* Clock pin (T_CLK) of touch screen */

/* Create an instance of the touch screen library */
TFT_Touch touch = TFT_Touch(DCS, DCLK, DIN, DOUT);


void setup()
{
  Serial.begin(115200);

  tft.init(); 

  
  // Set the TFT and touch screen to landscape orientation
  tft.setRotation(1);
  touch.setRotation(1);

  tft.fillScreen(TFT_BLACK);
  
 // TFT H_MAX = 800 & TFT V_MAX = 480 
//tft.fillRect(X_MIN, V_MAX - Y_MAX, X_MAX, Y_MAX, COLOR);//Only if Y coarse is Inverted!!

 tft.fillRect(400, 240, 400,240, TFT_WHITE);//half screen calibration test
 
//-------------BUTTONS---------------
 tft.fillRect(0, 380, 100, 100, TFT_RED);
 tft.fillRect(100, 380, 100, 100, TFT_BLUE);
 tft.fillRect(200, 380, 100, 100, TFT_GREEN);
 tft.fillRect(300, 380, 100, 100, TFT_YELLOW);

      
}


void loop()
{
  //int X_RawData;
  //int Y_RawData;
  int X_Coord;
  int Y_Coord;
  int X_RAW;
  int Y_RAW;

  // Check if the touch screen is currently pressed
  // Raw and coordinate values are stored within library at this instant
  // for later retrieval by GetRaw and GetCoord functions.

  if (touch.Pressed()) // Note this function updates coordinates stored within library variables
  {
    // Read the current X and Y axis as Raw co-ordinates at the last touch time
    // The values were captured when Pressed() was called!
    
    //Raw coordonates with 800x480 in TFT_Touch.cpp------------
    X_RAW = touch.X()- 100;
    Y_RAW = 170 - touch.Y()+ 180;//Y coarse inverted corrections
    
    //Remap X & Y Raw datas to fit the TFT resolution 
    X_Coord = map(X_RAW,0,530,0,800);
    Y_Coord = map(Y_RAW,0,220,0,480);
    
    //Debug Raw datas & coordonates in the monitor 
    Serial.println("X_RAW,Y_RAW :");
    Serial.print(X_RAW); Serial.print(","); Serial.println(Y_RAW);
    Serial.println("X_Coord,Y_Coord :");
    Serial.print(X_Coord); Serial.print(","); Serial.println(Y_Coord);
    Serial.println();
   
    //Button test verification on the monitor
    if(X_Coord>400 && X_Coord<800 && Y_Coord>25 && Y_Coord<240)
    Serial.println("WHITE PRESSED!");
    if(X_Coord>35 && X_Coord<135 && Y_Coord>25 && Y_Coord<100)
    Serial.println("RED PRESSED!");
    if(X_Coord>135 && X_Coord<235 && Y_Coord>25 && Y_Coord<100)
    Serial.println("BLUE PRESSED!");
    if(X_Coord>235 && X_Coord<335 && Y_Coord>25 && Y_Coord<100)
    Serial.println("GREEN PRESSED!");
    if(X_Coord>335 && X_Coord<435 && Y_Coord>25 && Y_Coord<100)
    Serial.println("YELLOW PRESSED!");
  }
}

**Comment by Bodmer** [comment]
Looks like you have it cracked now.  I think there are 8 orientation that the touch film can be installed in and the TFT_Touch library only handles 4 of them.  That library is quite old now and does not produce enough filtering for the touch position, that is required for some partiularly "noisy" setups.

For me this is the "goto" XPT2046 library which incorporates sophisticated filtering with good response time:
https://github.com/achillhasler/TFT_eTouch

It has examples compatible with TFT_eSPI.
