### ISSUE TITLE
Help Wanted: How to accomplish the hardware Hack on the 3.5" Pi Screen

### ISSUE THREAD

**Issue by wilhelmzeuschner** [Bodmer/TFT_eSPI#168]
I have some difficulties figuring out how to hack my TFT  screen with just the one image.
Therefore I'd greatly appreciate further documentation, images or a bit more detailed explanation.
I think that this 
![rpi_tft_mod](https://user-images.githubusercontent.com/37621765/42411464-89336cfa-81fc-11e8-9402-af9ebf0154d0.png) 
is just a small portion of a larger schematic. Having just the larger schematic would help a lot!

I'm fairly confident in what to do but I am not quite sure whether I am actually correct.

- "1Y" is the inverse of input "1A"
- Normally "1Y" would be connected directly to "WR" (, which is TFT_WR?)

If those two statemets were correct it wouldn't make any sense to connect "TFT_WR" through a diode and resistor to "1Y" if "WR" (which is the same as "TFT_WR"?) is connected without the previously mentioned diode, since both are (as far as I understand it) ~~essentially~~ the same pin on the TFT-ribbon.

My version of the screen has a slightly different PCB layout but the same components.

**Comment by Bodmer** [comment]
Your understanding of the schematic is correct.  The hack works because the HC04 can drive the line via the 470R when TFT_WR (driven by the ESP8266 or ESP32) is high. TFT_WR can also generate strobes and override the HC04 output by pulling TFT_WR low, meanwhile the current from the HC04 is limited by the 470R. So effectively this is a simple form of AND gate. The diode must be of a low capacitance type.

I do not recommend the hack unless you are confident you can put the circuit back as it was if you find it is unrelaible.

Here is a pic of my hack, but it is quite ugly!

[https://i.imgur.com/sSyqVOy.jpg](url)
