### ISSUE TITLE
ILI9341 + RP2040

### ISSUE THREAD

**Issue by kaefe64** [Bodmer/TFT_eSPI#1725]
Just to let you know that for me, the display ILI9341 only worked properly with the RP2040 when I changed the width and height in
TFT_eSPI/TFT_Drivers/ILI9341_Defines.h
#define TFT_WIDTH  320  //240
#define TFT_HEIGHT 240  //320

**Comment by Bodmer** [comment]
The ILI9342 requires that change because the default orientation is landscape. The ILI9342 is the display used in the M5Stack modules.

All ILI9341 devices I have come across default to portrait mode.

If you are not using an M5Stack module and have a bare display then please post a link to the vendors page as the displays may be of interest to others due to improved viewing angle in landscpe orientation.
