### ISSUE TITLE
SPIFFS warning and LittleFS compatibility

### ISSUE THREAD

**Issue by SheetLightning** [Bodmer/TFT_eSPI#1935]
I am working in Adruino IDE version 1.8.19 for now. The display works well so thank you for making this library public.

However, I wanted to ask about the following warning which I get when compiling a sketch which includes the TFT_eSPI library:

```
In file included from /home/johnc/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP8266.h:35,
                 from /home/johnc/Arduino/libraries/TFT_eSPI/TFT_eSPI.h:74,
                 from /home/johnc/Data/Data/Arduino/Calendar-Clock/Calendar-Clock.ino:52:
/home/johnc/.arduino15/packages/esp8266/hardware/esp8266/3.0.2/cores/esp8266/FS.h:275:15: note: declared here
  275 | extern fs::FS SPIFFS __attribute__((deprecated("SPIFFS has been deprecated. Please consider moving to LittleFS or other filesystems.")));
```

- Library version 1.2.1 is installed
- I am using an ESP8266 board
- the display is an ST7796 with SPI interface

I have enabled only the ST7796 driver in user config. I have connected only the TFT pins including GND+VCC, LED, CS, RESET, DC, SDI, SCK, this following instructions in the User_Setup.h file. I am not using the SD card or even touch at this time as the ESP8266 does not appear to have sufficient GPIO pins. I have now commented out:

`#define SMOOTH_FONT`

This has got rid of the warning, but since SPIFFS has now been deprecated for some time, I was wondering whether there are plans to update the library to make it compatible with LittleFS?

**Comment by Bodmer** [comment]
SPIFFS has been retained for compatibility with users legacy sketches. I will probably add a switch at some point so that SPIFFS has to be enabled in the setup if wanted,so the warning is avoided. The warning itself is part of the board package and not TFT_eSPI.

TFT_eSPI aready supports L:ittleFS, providing the more recent board support package is loaded for the ESP32/ESP8266/RP2040. LittleFS examples are provided.
