### ISSUE TITLE
GFX font question

### ISSUE THREAD

**Issue by rocketbob** [Bodmer/TFT_eSPI#207]
What's the procedure for generating a standard header file for a ttf font?

**Comment by Bodmer** [comment]
The font format is one conceived by Adafruit, you have a few options:

1. If you use Linux or are able to setup Mingw under windows then you can use the [tool provided by Adafruit here](https://github.com/adafruit/Adafruit-GFX-Library/tree/master/fontconvert).

2. You can use an online converter [such as this one](http://oleddisplay.squix.ch/#/home).

3. Also see info I posted here.

**Comment by rocketbob** [comment]
Awesome, thank you!

**Comment by marcschn** [comment]
Don't feel to open a new topic as it relates to @rocketbob question: what's the process for large fonts? both the adafruit tool and the online converter fail at large fonts (for example OpenSans >56pt).

**Comment by Bodmer** [comment]
Adafruit chose to use a signed 8 bit value for the font size and coordinate parameters, this can overflow for large fonts and thus constrains the maximum font size.

**Comment by marcschn** [comment]
Thanks for your quick reply. That's unfortunate. Do the same limitations apply to your vlw antialiased font implementation? I'd rather use some sort of font than have to generate single bitmaps for each char... :see_no_evil:

**Comment by Bodmer** [comment]
Yes, there are limits also with smooth fonts but you should be able to use fonts up to ~200 pixels high. 8 bit values are used to save on memory space but making them 16 bit would only require minor changes to the library because the vlw font files themselves use 32 bit numbers!

The squix online converter for Adafruit fonts fails above a 100 point size, but works at 100.
