### ISSUE TITLE
fillRect() doesn't show anything on the display when given negative width or height value (it works when using adafruit lib)

### ISSUE THREAD

**Issue by awocrf** [Bodmer/TFT_eSPI#2106]
fillRect() doesn't show anything on the display when given negative width or height value. It is working when I'm using the Adafruit library.

PlatformIO
v2.4.78
RP2040 uC
ILI9341
SPI

**Comment by Bodmer** [comment]
Yes, negative widths, heights and radii are rejected in this library for graphics, images, sprites and viewports. I won't be changing this so extra code will be needed in your sketch to cover your use case.

**Comment by Bodmer** [comment]
I think the Adafruit library is inconsistent in the behaviour with negative widths and/or heights, sometimes it draws with incorrect size, in other cases it draws nothing. This suggests the Adafruit_GFX library behaviour with negative values is by accident and not by design.

I believe the TFT_eSPI library behaves consistently and is therefore correct.
