### ISSUE TITLE
Feature Request: Non-Arduino Pico SDK Version

### ISSUE THREAD

**Issue by DatanoiseTV** [Bodmer/TFT_eSPI#2108]
Is there a plan releasing this library for the Pico SDK without pulling in all Arduino Abstraction?
Would be awesome to see it. Especially seeing that there is now RP2040 support from LVGL.

I have designed a RP2040 based tool which should allow to be used as stand-alone VT100 terminal,
USB Enumerator, I2C Scanner etc. and I need to use the Pico SDK in order to implement USB Host Mode
and to pull in FreeRTOS.

![image](https://user-images.githubusercontent.com/6614616/197561580-08a75827-ed2e-4ff1-b43e-e3d3b79c4659.png)

![image](https://user-images.githubusercontent.com/6614616/197561853-259f7b1e-6be7-465f-b45d-9711d176d253.png)

**Comment by Bodmer** [comment]
Unlikely to make that move because this is primarily an Arduino library and thus carries that heritage in the examples and support libraries etc!

The excellent [Earl Philhower package](https://github.com/earlephilhower/arduino-pico) is based on the RP2040 SDK, so all SDK functions are available under the Arduino layer and it supports FreeRTOS SMP. Worth a try if you have not investigated that library previously.
