### ISSUE TITLE
smooth fonts from sd card.

### ISSUE THREAD

**Issue by Andrejkos** [Bodmer/TFT_eSPI#2253]
Здравствуйте. Можно ли исправить артефакты, показанные на фото, при отображении гладкого шрифта из SD card.? Такие же артефакты и при отображении BMP-иконок.
Я использую плату ESP32 DEVKIT V1, TFT (320*480, SPI)  драйвер ILI9486 либо ST7796. Скетч из ваших примеров.

Hello. Is it possible to fix the artifacts shown in the photo when displaying a smooth font from an SD card.? The same artifacts are also present when displaying BMP icons.
I am using an ESP 32 DEVKIT V1 board, a TFT (320*480, SPI) ILI9486 or ST7796 driver. A sketch from your examples.

![smooth_fonts_from_SPIFFS](https://user-images.githubusercontent.com/111911872/207668983-039bfe6b-bfc4-4f2a-bb70-5f39db16288c.jpg)
![smooth_fonts_from_SD1](https://user-images.githubusercontent.com/111911872/207668998-90259b50-850b-457b-95f7-31b20d8b4796.jpg)

**Comment by Bodmer** [comment]
This is a system level issue rather than a library issue.

There are a number of reasons this can hapen, for example some SD cards and SD libraries do not work well. A scan of the Discussions section may help as other users have solved issues with SD cards for jepg drawing.

The simplest and best option is to put the SD card on an independant SPI bus to the TFT.

**Comment by Andrejkos** [comment]
Спасибо
