### ISSUE TITLE
Full Screen Sprites No Longer Work

### ISSUE THREAD

**Issue by NerdyCrafter** [Bodmer/TFT_eSPI#2652]
Arduino version 2.1.0, library version 2.5.0, esp32 board manager 2.0.9
Hardware: WEMOS d1 Mini ESP32, ST7789 1.3" LCD

At first I thought sprites just weren't working, but it turns out they no longer work when taking up the full screen. In my user setup the screen is set to 240x240, when I attempt to make a 240x240 sprite it will not appear on the screen. If the sprite is just one pixel smaller(239x239) it appears fine. The same code I wrote that used to work fine using full screen sprites no longer works.

Example of code that doesn't work anymore:

```
#include <TFT_eSPI.h> //Graphics library for display

TFT_eSPI tft = TFT_eSPI(); //Declares tft as object
TFT_eSprite img = TFT_eSprite(&tft);//img sprite


void setup() {

  tft.init(); // Initiates tft display

  tft.fillScreen(TFT_WHITE); // Fills TFT screen with white
  
  img.createSprite(240,240);
  img.fillScreen(TFT_BLUE);
  img.fillCircle(100,100,50,TFT_RED);
  img.pushSprite(0,0);

}


// Code that loops continusly(main program)
void loop() {

}
```

**Comment by Bodmer** [comment]
A 240x240 16bit sprite will require ~115 kbytes RAM so that uses most of the available memory. Around 80kbytes used to be the approximate limit but Espressif increased the limit in later board packages so I suspect the 2.0.9 package has lowered the available RAM.

To solve this either downgrade the board package to the last one that worker or purchase a board with PSRAM fitted.

Reducing the colour bit depth, e.g. to 8 bits would halve the RAM demand, but may not be suitable for your use case.
