### ISSUE TITLE
ESP32-S3 module does not have such output

### ISSUE THREAD

**Issue by brightproject** [Bodmer/TFT_eSPI#2771]
In the display [setting,](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setups/Setup70d_ILI9488_S3_Parallel.h) `pin 34` assign to `RST` is indicated.
As the name suggests, this is a setting for the `ESP32-S3`, but it does not have such an `I/O` port.
Why allocate a separate pin at all, occupy the leg of the microcontroller, if you can simply solder this `RESET` to +3.3 volts?

**Comment by Bodmer** [comment]
The ESP32 S3 has GPIO in the range 0-48, not all are available for general use and some boards only break out a subset. If GPIO 34 is not available on your board then an alternative can be used.

The use of a hardware reset pin is advisable, otherwise the display is only hardware reset at power up and by software commanded reset. Since the processor pins are undefined for the boot period, some displays lock up due to spurious transients on the pins and then a software reset fails to initialise the display. If your display works reliably with the RST line tied high, then you do not need to use a GPIO line to drive it.
