### ISSUE TITLE
Weird positioning

### ISSUE THREAD

**Issue by themakerbro** [Bodmer/TFT_eSPI#309]
Thanks for the port to NodeMCU. I just tried it and get a weird wrap-around (see attached image) for the default sketch. Any suggestions?

The screen is a 1.44" 128x128 ST7735 TFT.

![img_5896](https://user-images.githubusercontent.com/7302561/52918110-2ea57280-32a8-11e9-82f0-3a9771fdac8f.JPG)

**Comment by Bodmer** [comment]
The skew is due to a change in the setAddrWindow parameter. I have updated the Github example.

The offset is due to the display driver having a pixel offset. Try different rotations, you should find one rotation that has no offset.

The offset happens because the controller can drive a display with more pixels, so it is dependant on the way the manufacturer wires up the pixels.

**Comment by themakerbro** [comment]
Ah, I see. I hadn't gotten a chance to dig into the code and you already solved it. Thanks so much!

![screen shot 2019-02-17 at 7 24 21 pm](https://user-images.githubusercontent.com/7302561/52926195-9fb94a00-32e9-11e9-98c8-c9f0755bc053.png)

**Comment by Bodmer** [comment]
Great.
Note that I never got around to making the sketch support 2 eyes...
