### ISSUE TITLE
STM32F103 support

### ISSUE THREAD

**Issue by arnold-b** [Bodmer/TFT_eSPI#432]
Hello, 

I like this library. Its the only one which realy works. 
Is there any posibility that you could add STM support there. 
Display Power Mode: 0x6E
MADCTL Mode: 0x7F
Pixel Format: 0x7F
Image Format: 0x77
Self Diagnostic: 0x7F
always diffrent values
Thanks

**Comment by Bodmer** [comment]
I will think on this further. At the moment I do not have enpugh spare time to make and test the changes. The adaption is further complicated because some capabilities, like SPIFFS are espressif specific.
I am hoping to find time to write a library user manual before making any significant changes to the library.

**Comment by Bodmer** [comment]
It appears that [SEEED Studio have adapted the library](https://github.com/Seeed-Studio/Seeed_Arduino_LCD) in a way that could support STM processors.
