### ISSUE TITLE
Wrong font rendering at the edge of the screen

### ISSUE THREAD

**Issue by kostuch** [Bodmer/TFT_eSPI#479]
Test case (on the 320x240 landscape screen):

tft.setTextColor(TFT_GREEN, TFT_BLACK); 
tft.setCursor (0, 220);
tft.setTextFont(4);        
tft.print("Test text - nothing really fancy!");

Characters should be clipped, but here is wrapped and overwrite itself.
Other sizes also have this issue when text do not fit physical screen.

![test](https://user-images.githubusercontent.com/9976331/69547303-9f935c80-0f95-11ea-822f-4f1f6cede2ab.jpg)

**Comment by Bodmer** [comment]
This is down to history, the fonts are run length encoded, this is for [very fast rendering on an UNO/Mega](https://www.youtube.com/watch?v=1D4hkqZc3b8)  where speed the impact of cropping checks was very significant (due to very limited processing power). The viewpoint being that if text is partly off screen then there is a problem with the sketch... so why compromise performance.  Of course now the ESPxxx processors have more power to do thee things...

The simple way around this is to not draw text at the edges off the screen. The library will manage this  for the print class via cursor manipulation if you enable wrap on x and y axes using function setTextWrap(boolean wrapX, boolean wrapY = false), wrapping on y axis is off by default, to turn on:

```tft.setTextWrap(true, true);```
