### ISSUE TITLE
Driver selection need library changes

### ISSUE THREAD

**Issue by petrkr** [Bodmer/TFT_eSPI#596]
Think how do interface so driver choose will NOT need change files in library. In generic edit library is bad idea. First is because by long time you will forgot about those changes and second is you should never change code of libraries downloaded over "library manager".

I suggest do some way how ucglib or u8g2 does.

Mark this as feature request.

**Comment by Bodmer** [comment]
I understand the issue and this has been raised a few times in #29, #67, #97, #240. It is due to a limitation imposed by the Arduino IDE to avoid #define conflicts in sketch and library.

The main advantage of the approach taken is that the examples all run without modification once the setup is defined. As I have at least 12 different display hardware test setups it would mean I need 12 copies of each example sketch or edit every sketch to test with each hardware setup...

So for me all that needs to be done to change hardware setups is add // and remove // in a couple of lines in the User_Setup_Select.h file which is very quick and easy. I also write the correct setup file number on each board configuration for easy reference. Other library examples such as those with Dark Sky weather or TFT_eFEX also run without modification.

You can define your own setup in the folder User Setups, see comments in the setup files. As User_Setup_Select.h uses a files path to the setup file you can add your own folder and save setups there. It is best to make a copy of your setup files and folder before updating the library.

If you migrate to the PlatformIO IDE you can define the setup as part of your project.
