### ISSUE TITLE
Question? Drawstring/float beyond screen edge

### ISSUE THREAD

**Issue by tablatronix** [Bodmer/TFT_eSPI#644]
How can I push this float closer to the bottom edge, it is a float and has no descenders, I assume that is why I cannot. Also I cannot seem to pass a y larger than the screen width(height) to push it down..
![7883DC89-C11A-4797-9903-6B03437F2F20](https://user-images.githubusercontent.com/807787/83204571-c5024e00-a111-11ea-9eac-0b15d27c7622.jpeg)

**Comment by Bodmer** [comment]
This is a historical limitation of the font rendering approach for the Run Length Encoded fonts. The library automatically pulls the character back to the screen area otherwise the character image gets corrupted. The code could be changed but it would then render characters more slowly, This font rendering approach was developed many years ago for the UNO/Mega to improve font rendering performance. There is no simple solution unless Sprites are used.  Smooth fonts (stored in FLASH rather than in SPIFFS to improve performance) will work though there will be a performance penalty and you will get flickering unless Sprites are used.

**Comment by Bodmer** [comment]
I have updated the library to allow partially off screen RLE font rendering. (now version 2.2.11)
