### ISSUE TITLE
Slow performance 

### ISSUE THREAD

**Issue by ex3ndr** [Bodmer/TFT_eSPI#650]
Thank you for your library! It works really fast while i am challenging it to be must faster. I want to achieve 60fps with double buffering on 320x240 display.

I got very beefy Teensy 4.1 for my work, using hardware SPI with ST7789v driver with display similar to Adafruit's one: https://learn.adafruit.com/2-0-inch-320-x-240-color-ips-tft-display

I am using 70mhz SPI speed (working good). Bumping to 80mhz

I am doing very simple double buffer rendering with sprite size of display:
```

// Render Rounded Rect
unsigned long t = millis();
int offset = floor(100 * sin(((double)(time - t)) / ((double) 1000)));
backBuffer.fillSprite(TFT_BLACK);
backBuffer.drawRoundRect(10, 100 + offset, 100, 100, 16, TFT_GREEN);

// Push backBuffer
backBuffer.pushSprite(0, 0);
```

Weird thing that drawing to sprite yields ~4600 FPS.

Once i will try to push sprites to display i am getting only 25 fps. Also it seems that overclocking Teensy will yield better performance. How it is possible that 600MHZ is not enough to push data to SPI while it is ok to perform drawing itself.

**Comment by Bodmer** [comment]
The high frame rate in a Sprite is to be expected because this involved writing blocks of data to memory, which is a basic capability of all processors.
The SPI data transfer to a TFT will be much slower because dat is clocked out bit by bit. At 80MHz the highest possible frame rate for a 240x320 display can be calculated as 65fps but it will be difficult to achieve this error free as the displays are only specified for operation up to around 25MHz. Typically these displays do operate at higher rates than the data sheet figures, but this is not guaranteed.

The reason you are getting 25fps not 65fps is that the TFT_eSPI library is that the SPI not optimised for Teensy boards, but the stock Arduino SPI library is used which writes 1 byte at a time.  To get close to the 65fps will require optimized drivers that for example use the FIFO built into the processor.
I am not sure if the ILI9341_t3 library will run on a Teensy 4.0, if it does it would be worth seeing what frame rate you get wehn copying a screen buffer in RAM to the display. If you get the rate you need then you could load both ILI9341_t3 and TFT_eSPI libraries, then use the Sprite features in the TFT_eSPI library but write the image to the screen using the ILI9341_t3 library.
I was given a Teensy3.0 some time ago but I have not used it, I prefer ESP32 or STM32 based boards and have no plans to add optimisation for Teensy boards.
I suspect if you can get the frame rate up to near 60fps with 80MHz SPI you will start to see that the display cannot cope with the pixel rate and start to get corrupted pixels.

With TFT_eSPI and a STM32F767 processor I managed to get >100fps to the screen but that is with an 8 bit parallel bus driver which has been "tuned" for the STM32 processor.
