### ISSUE TITLE
ili9486 working schematic

### ISSUE THREAD

**Issue by clear-sky** [Bodmer/TFT_eSPI#832]
hi all and thanks for this great driver
i have 3.5 inch ili9486 
http://aitendo3.sakura.ne.jp/aitendo_data/product_img/lcd/tft2/Z350IT002/Z350IT002_aitendo.pdf
and want to make a pcb for use it in spi mode and found these schematics
![sch](https://user-images.githubusercontent.com/6883905/99886509-4a466580-2c52-11eb-8523-7a0a7e79e5b9.jpg)
![img3](https://user-images.githubusercontent.com/6883905/99886525-7235c900-2c52-11eb-8c0e-17534e938e86.png)
![2d25eed4-3a79-11e4-8418-b8439db1cc4f](https://user-images.githubusercontent.com/6883905/99886601-0bfd7600-2c53-11eb-986f-ee3b65d3e542.png)
my question is which is compatible with this driver

**Comment by pipi61** [comment]
https://forum.arduino.cc/index.php?topic=443787.90

**Comment by Bodmer** [comment]
I do not recommend any of those circuits because they are poorly designed and rely on a logic race hazzard. This means they only operate over a limtied frequency range.

I suggest you connect your processor direct to the display, either with a SPI interface or 8 bit parallel interface. Study the data sheet and build a wired prototype before commiting to a PCB.
