### ISSUE TITLE
What tool is used to create RLE fonts?

### ISSUE THREAD

**Issue by Murloc992** [Bodmer/TFT_eSPI#855]
Hello,

I was wondering what tool should be used to create my own compatible RLE compressed font source files?

I was using LCD-Image-Converter for a long time but it doesn't seem like the format in use here.

I would really love to know what tool has been used. :)

**Comment by Bodmer** [comment]
A long time ago I write an Arduino sketch that created the fonts from bitmaps, this then needed some manual editting. The bitmaps were generated by a software tool from crystalfontz which does not seem to exist anymore. Unfortunately during a PC upgrade the sketch and tool was lost. Writing again from scratch is on my todo list but is not a priority due to paid for work at the moment.

FYI a character is drawn as a raster scan within a box size of the characters width and global font height. The RLE format is a byte, the top bit is a flag, the least significant 7 bits are a 7 bit number (0-127). If the flag is 1 then foreground pixels are plotted, if it is 0 the background pixels are plotted. The number of pixels to plot is the 7 bit number +1.

So, for example, the encoded sequence "0x81, 0x1F" means plot 2 pixels in foreground then 32 pixels in background.

You could manually generate a single character using some squared paper and a pencil and replace the one in an existing file.
